% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Einföldun},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{amsthm}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{verbatim}
\usepackage{hyperref}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[icelandic]{babel}
\hypersetup{colorlinks,allcolors=blue}
\usepackage{enumerate}
\usepackage{lastpage}
\usepackage[shortlabels]{enumitem}
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[R]{Þórarinn Jónmundsson}
\fancyhead[C]{Dæmi um skýrslu}
\fancyhead[L]{Sumarverkefni}
\fancyfoot[L]{Háskóli Íslands}
\fancyfoot[R]{\thepage}
\usepackage{float}
\usepackage{algorithm}
\usepackage{algorithmicx}
\usepackage{algpseudocode}
\usepackage{caption}
\usepackage[sectionbib]{chapterbib}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\title{Einföldun}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

%\begin{titlepage}
%\thispagestyle{empty}
\begin{center}
\LARGE{\textbf{Sumarverkefni}}\\
\vspace*{2\baselineskip}
\Large{\textbf{Dæmi um skýrslu}}
\end{center}
% \end{titlepage}
\thispagestyle{empty}
\newpage

\hypertarget{inngangur}{%
\section{Inngangur}\label{inngangur}}

Aðeins til að byrja, þetta er tilraun hjá mér í að ná að orða hluti aðeins betur og koma gögnunum fram á skiljanlegan hátt. Það vantar líklega enn aðeins upp á það. En það er markmið skýrslunar hér.

Nú, rannsóknarspurninginn sem verið er að vinna með hér er:

Er hægt að mæla framfarir en ekki bara utanaðbókarlærdóm? Bera saman fyrstu svarmöguleika og þá sem hafa komið áður.

\hypertarget{guxf6gninn}{%
\section{Gögninn}\label{guxf6gninn}}

Til að byrja með, er gott að skoða gögninn. Ég hef fjarlægt sumar breytur, þar sem þær voru ruglingslegar og óþarfi.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hashAnswer <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{'Data/hashAnswer4.csv'}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{subset}\NormalTok{(}\DataTypeTok{select =} \OperatorTok{-}\KeywordTok{c}\NormalTok{(timeStart, fsvfat, fsvfatu, X))}
\NormalTok{hashAnswer}\OperatorTok{$}\NormalTok{hsta <-}\StringTok{ }\NormalTok{hashAnswer}\OperatorTok{$}\NormalTok{hsta}\OperatorTok{%>%}\KeywordTok{as.character}\NormalTok{()}
\NormalTok{hashAnswer}\OperatorTok{$}\NormalTok{lectureId <-}\StringTok{ }\NormalTok{hashAnswer}\OperatorTok{$}\NormalTok{lectureId }\OperatorTok{%>%}\StringTok{ }\KeywordTok{as.factor}\NormalTok{()}
\NormalTok{hashAnswer}\OperatorTok{$}\NormalTok{studentId <-}\StringTok{ }\NormalTok{hashAnswer}\OperatorTok{$}\NormalTok{studentId }\OperatorTok{%>%}\StringTok{ }\KeywordTok{as.factor}\NormalTok{()}
\NormalTok{hashAnswer}\OperatorTok{$}\NormalTok{nicc <-}\StringTok{ }\NormalTok{hashAnswer}\OperatorTok{$}\NormalTok{nicc }\OperatorTok{%>%}\StringTok{ }\KeywordTok{as.factor}\NormalTok{()}
\NormalTok{hashAnswer }\OperatorTok{%>%}\StringTok{ }\KeywordTok{glimpse}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 115,197
## Columns: 10
## $ lectureId  <fct> 3082, 3082, 3082, 3082, 3082, 3082, 3082, 3082, 3082, 30...
## $ studentId  <fct> 1, 1, 1, 1, 1, 18788, 18788, 18788, 18788, 18788, 18788,...
## $ questionId <int> 45591, 44899, 45647, 45647, 45647, 44920, 45021, 45480, ...
## $ correct    <int> 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,...
## $ hash       <chr> "d3a978206c877eee8627a29c7a94238d8339d66fc4be460d9e6b6cb...
## $ fsfat      <int> 0, 1, 2, 2, 2, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 10, 1...
## $ hsta       <chr> "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "...
## $ timeDif    <int> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 254, NA, NA,...
## $ nicc       <fct> 3, 3, 3, 3, 3, 3, 7, 3, 3, 4, 5, 6, 6, 5, 3, 3, 3, 3, 7,...
## $ gpow       <dbl> 8.2506619, 8.2506619, 8.2506619, 8.2506619, 8.2506619, 0...
\end{verbatim}

Gagnasettið, eins og það er núna hefur 10 breytur. Breyturnar eru:

\begin{itemize}
\item
  lectureId: Þetta er Id breyta fyrir hvaða fyrirlestur við erum í.
\item
  studentId: Þetta er Id breyta fyrir hvaða nemenda við erum með.
\item
  questionId: Þetta er Id breyta fyrir hvaða spurningu við erum með.
\item
  correct: Þetta er binary breyta sem segir til hvort það var svarað rétt eða rangt.
\item
  hash: Þetta er hash breyta sem segir til hvaða rétta svar við erum með hérna
\item
  fsfat: ``fjöldi spurninga fram að þessu'' þetta segir til um hve margar spurningar nemandinn hefur svarað hingað til, innan við þennan fyrirlestur. Talning byrjar á 0.
\item
  hsta: ``hef séð þetta áður'' er breyta sem segir til um hvort að nemandinn hefur séð rétta svarið áður eða ekki
\item
  timeDif: Þetta er breyta sem segir okkur hve langt það var séðan nemandinn sá þetta svar áður.
\item
  nicc: þetta er ``number of incorrect choices'', líke þekkt sem NumQ. Segir til hve margir rangir svarmöguleikar það eru.
\item
  gpow: gpow er breyta sem er sett á nemenda þegar hann byrjar á fyrirlestrinum sem segir til hve hratt hann fær erfiðari spurningar.
\end{itemize}

\hypertarget{teikningar-og-tuxf6flur}{%
\section{Teikningar og töflur}\label{teikningar-og-tuxf6flur}}

Fyrsta sem er gott að gera, er að skoða aðeins gögninn sjálf.

\hypertarget{skouxf0auxf0-fyrir-uxf6ll-guxf6gninn}{%
\subsection{skoðað fyrir öll gögninn}\label{skouxf0auxf0-fyrir-uxf6ll-guxf6gninn}}

Byrjum aðeins á því að skoða hve mikið af gögnunum eru nemendur að sjá nýtt svar á móti gömlu svari.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(hashAnswer, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ hsta)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{Simplify_files/figure-latex/unnamed-chunk-1-1.pdf}

Það lítur út fyrir að vera mikið meira af gögnunum sem eru svör sem hafa sést áður á móti nýjum svörum.
Þar sem u.þ.b. 2/3 af gögnunum eru spurningar með rétt svör sem hafa sést áður á meðan 1/3 af gögnunum eru spurningar með rétt svör sem eru að sjást í fyrsta sinn.

Nú markmiðið er að geta skoðað framfarir nemenda, ekki bara utanaðbókarlærdóm, svo það væri gott að setja upp graf sem inniheldur meðaltal réttra svara fyrir hvert fsfa og skipt eftir hsta. Semsagt meðaltal réttra svara hjá þeim sem hafa séð x margar spurningar hingað til, bæði fyrir þann fjölda sem hefur séð rétta svarið áður og þau sem hafa það ekki.

\begin{figure}
\centering
\includegraphics{Imgsimplify/plotbymean.png}
\caption{plot by mean}
\end{figure}

Það er nú smá erfitt að lesa þessa mynd, það lítur út fyrir að vera smá vaxi hjá þeim sem eru að sjá þetta í fyrsta skiptið, svo fellur það niður og aftur upp. Svo er dreifnin að vaxa því lengra sem er farið. Skoðum aðeins stærð gagnanna fyrir hvern punkt til að sjá hvað er að gerast

\begin{figure}
\centering
\includegraphics{Imgsimplify/plotbyamount.png}
\caption{plot by sum}
\end{figure}

Hérna kemur skýringinn, það lítur út fyrir að vera stórt fall af gögnum sem eru að sjá svar í fyrsta sinn því lengra sem er farið, og líka hjá þeim sem hafa séð svarið áður. Þetta er líklega útaf því að hver nemandi fer mismunandi langt og sumir nemendur geta verið að fara lengur en hinir. Skoðum aðeins hlutföll gagnanna til að skoða þetta betur.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{a <-}\StringTok{ }\NormalTok{hashAnswer }\OperatorTok{%>%}\StringTok{ }\KeywordTok{summarise}\NormalTok{(}\StringTok{"FY50"}\NormalTok{ =}\StringTok{ }\KeywordTok{sum}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{50}\NormalTok{), }\StringTok{"FY100"}\NormalTok{ =}\StringTok{ }\KeywordTok{sum}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{100}\NormalTok{), }
                              \StringTok{"FY150"}\NormalTok{ =}\StringTok{ }\KeywordTok{sum}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{150}\NormalTok{), }\StringTok{"FY200"}\NormalTok{ =}\StringTok{ }\KeywordTok{sum}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{200}\NormalTok{), }
                              \StringTok{"FY250"}\NormalTok{ =}\StringTok{ }\KeywordTok{sum}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{250}\NormalTok{), }\StringTok{"FY300"}\NormalTok{ =}\StringTok{ }\KeywordTok{sum}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{300}\NormalTok{))}
\NormalTok{b <-}\StringTok{ }\NormalTok{hashAnswer }\OperatorTok{%>%}\StringTok{ }\KeywordTok{summarise}\NormalTok{(}\StringTok{"HY50"}\NormalTok{ =}\StringTok{ }\KeywordTok{mean}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{50}\NormalTok{), }\StringTok{"HY100"}\NormalTok{ =}\StringTok{ }\KeywordTok{mean}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{100}\NormalTok{), }
                              \StringTok{"HY150"}\NormalTok{ =}\StringTok{ }\KeywordTok{mean}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{150}\NormalTok{), }\StringTok{"HY200"}\NormalTok{ =}\StringTok{ }\KeywordTok{mean}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{200}\NormalTok{), }
                              \StringTok{"HY250"}\NormalTok{ =}\StringTok{ }\KeywordTok{mean}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{250}\NormalTok{), }\StringTok{"HY300"}\NormalTok{ =}\StringTok{ }\KeywordTok{mean}\NormalTok{(fsfat }\OperatorTok{>=}\StringTok{ }\DecValTok{300}\NormalTok{))}
\NormalTok{ab <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(a, b)}
\NormalTok{FHbylim <-}\StringTok{ }\NormalTok{ab }\OperatorTok{%>%}\StringTok{ }\KeywordTok{pivot_longer}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\StringTok{'FY50'}\NormalTok{, }\StringTok{'HY50'}\NormalTok{, }\StringTok{'FY100'}\NormalTok{, }\StringTok{'HY100'}\NormalTok{, }\StringTok{'FY150'}\NormalTok{, }\StringTok{'HY150'}\NormalTok{, }\StringTok{'FY200'}\NormalTok{, }\StringTok{'HY200'}\NormalTok{, }\StringTok{'FY250'}\NormalTok{, }\StringTok{'HY250'}\NormalTok{, }\StringTok{'FY300'}\NormalTok{, }\StringTok{'HY300'}\NormalTok{), }
                    \DataTypeTok{names_to =} \StringTok{"typewLim"}\NormalTok{, }\DataTypeTok{values_to =} \StringTok{"values"}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{separate}\NormalTok{(typewLim, }\DataTypeTok{into =} \KeywordTok{c}\NormalTok{(}\StringTok{"type"}\NormalTok{, }\StringTok{"limit"}\NormalTok{), }\DataTypeTok{sep =} \DecValTok{2}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{pivot_wider}\NormalTok{(}\DataTypeTok{names_from =}\NormalTok{ type, }\DataTypeTok{values_from =}\NormalTok{ values)}


\NormalTok{FHbylim }\OperatorTok{%>%}\StringTok{ }\KeywordTok{kable}\NormalTok{(}\DataTypeTok{digits =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{tabular}{l|r|r}
\hline
limit & FY & HY\\
\hline
50 & 31964 & 0.2775\\
\hline
100 & 9553 & 0.0829\\
\hline
150 & 3204 & 0.0278\\
\hline
200 & 1149 & 0.0100\\
\hline
250 & 332 & 0.0029\\
\hline
300 & 84 & 0.0007\\
\hline
\end{tabular}

Lítur út fyrir að um 27.75\% gagnanna eru af spurningum sem fara yfir 50 fsfat og bara u.þ.b. 8.29\% gagnanna sem fara yfir 100. Hugmynd er þá að skera af gögninn miðað við 50 fsfat eða 100 fsfat. Skoðum þá aðeins hlutfall hsta og meðtalals grafið að ofan miðað við það.

\hypertarget{skouxf0auxf0-eftir-limit}{%
\subsection{Skoðað eftir limit}\label{skouxf0auxf0-eftir-limit}}

Fyrst er að setja upp gögninn. Að auki fjarlægji ég nemendur sem svöruðu ekki fleiri en 7 spurningum samtals

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hashLim50 <-}\StringTok{ }\NormalTok{hashAnswer }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(studentId) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\StringTok{"count"}\NormalTok{ =}\StringTok{ }\KeywordTok{n}\NormalTok{()) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(count }\OperatorTok{>}\StringTok{ }\DecValTok{7} \OperatorTok{&}\StringTok{ }\NormalTok{fsfat }\OperatorTok{<}\StringTok{ }\DecValTok{50}\NormalTok{)}
\NormalTok{hashLim100 <-}\StringTok{ }\NormalTok{hashAnswer }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(studentId) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\StringTok{"count"}\NormalTok{ =}\StringTok{ }\KeywordTok{n}\NormalTok{()) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(count }\OperatorTok{>}\StringTok{ }\DecValTok{7} \OperatorTok{&}\StringTok{ }\NormalTok{fsfat }\OperatorTok{<}\StringTok{ }\DecValTok{100}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Skoðum hlutfallið aftur hjá hsta.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(hashLim50, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ hsta)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"undir 50"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Simplify_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(hashLim100, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ hsta)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"undir 100"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Simplify_files/figure-latex/unnamed-chunk-3-2.pdf}

Það sést að ef við tökum bara undir 50, þá er hsta orðið miklu nær og þegar við erum með undir 100, þá erum við kominn nálægt ójöfnunni eins og áðan.

Gott að skoða meðaltals myndina aftur, eftir að skera eftir limit.

\includegraphics{Imgsimplify/plotbymean50.png}
\includegraphics{Imgsimplify/plotbymean100.png}

Nú sést aðeins betur hvað er að gerast, í fyrri sjáum við að það lítur út fyrir að vera árangur og framfarir. Þar sem báðar línunar eru að vaxa þegar fleiri spurninga hefur verið svarað. En það sést á seinni myndini að það fer að jafna sig eftir það og framfarir hætta. Svo er það eitthvað smá fall hjá nýjum svörum.

\hypertarget{umruxe6uxf0ur}{%
\subsection{umræður}\label{umruxe6uxf0ur}}

Þá kemur spurninginn hvort þetta er nokkuð framfarir eða utanaðbókarlærdómur, í fyrri þá lítur út fyrir að líkurnar vaxa. En það virðist svo jafna sig eftir það.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Ein hugmynd um hvað er að gerast þar er að þetta er ekki framfarir sem er að vaxa, heldur er það utanaðbókarlærdómur á röngu svarmöguleikunum, Það gæti verið aðal áhrifinn þar. Hugmynd til að skoða það betur væri kannski að skoða eins mynd, nema filterað bara fyrir spurningarnar sem hafa rétt svör sem eru að sjást í fyrsta skiptið og gert flokka fyrir hlutfall rangra svara sem hafa sést áður. Þá mun koma ein lína fyrir hvert hlutfall, ef það er allt beinar láréttar línur, þá gæti það bent til að verið sé að ræða utanaðbókarlærdómur sem aðal áhrifin.
\item
  Önnur hugmynd er að ef við gætum skipt nemendum upp í flokka, sem nemendur sem setja allt á minnið og nemendur sem eru að læra og fá framfarir. Svo er spurning hvort framfarirnar sjást betur þa.
\item
  Loka hugmynd er að í staðinn fyrir að skoða fsfat eftir fyrirlestri, að skoða það kannski frekar eftir spurningahaus, þá gæti sést betur áhrif á sambærilegum spurningum eftir því hve margar tilraunir nemandinn hefur fengið á spurninguna sjálfa.
\end{enumerate}

\hypertarget{modelgeruxf0}{%
\section{Modelgerð}\label{modelgeruxf0}}

Hér er smá grunnur af því sem ég er kominn með fyrir modelgerðina.

Ég byrjaði að skoða einföld glm, en þar sem það er verið að ræða um mixed effect model, þá hef ég fært yfir í glmer í staðinn. Ég ákvað að keyra allt miðað við 100 limitinn, ég hef ekki neina sterka ástæðu enn, þar sem ég veit ekki um leið til að sýna hvort einn gagnasett er betri en hitt, svo mér fannst 100 vera nægilega gott í bili.

\hypertarget{gagnavinnsla}{%
\subsection{gagnavinnsla}\label{gagnavinnsla}}

Fyrsta sem þarf að gera, er smá gagnavinnsla. Glmer tekur ekki vel við háu tölunum í fsfat, svo ég deili með 10 til að fá glmer til að keyra almennilega

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hashLim100}\OperatorTok{$}\NormalTok{fsfat <-}\StringTok{ }\NormalTok{hashLim100}\OperatorTok{$}\NormalTok{fsfat}\OperatorTok{/}\DecValTok{10}
\end{Highlighting}
\end{Shaded}

\hypertarget{modelin-sjuxe1lf}{%
\subsection{modelin sjálf}\label{modelin-sjuxe1lf}}

Modelinn sem ég er að vinna með á þessum tímapunkti er

\begin{itemize}
\item
  glmer(correct \textasciitilde{} fsfat*hsta + nicc + gpow + lectureId + (1 \textbar{} studentId), family = binomial(link = ``logit''), \ldots)
\item
  glmer(correct \textasciitilde{} fsfat*hsta + nicc + gpow + lectureId + (1 + fsfat * hsta \textbar{} studentId), family = binomial(link = ``logit''), \ldots)
\end{itemize}

Stóri munurinn milli þeirra er að ég hef meira í mixed effect modelinu seinna en í því fyrra

Ég keyri módelinn ekki hér, því þau eru of löng, en hef save-að þau til seinni notkunar, svo hægt sé að load-a þeim upp

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Þetta er fyrri modelið}
\KeywordTok{load}\NormalTok{(}\StringTok{"Data/ans22"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Registered S3 methods overwritten by 'lme4':
##   method                          from
##   cooks.distance.influence.merMod car 
##   influence.merMod                car 
##   dfbeta.influence.merMod         car 
##   dfbetas.influence.merMod        car
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Þetta er seinna modelið}
\KeywordTok{load}\NormalTok{(}\StringTok{"Data/ans42"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{smuxe1-model-analysis}{%
\subsection{smá model Analysis}\label{smuxe1-model-analysis}}

Summaríið þeirra er svo

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(ans22)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: correct ~ fsfat * hsta + nicc + gpow + lectureId + (1 | studentId)
##    Data: hashTest2
## Control: glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05))
## 
##      AIC      BIC   logLik deviance df.resid 
##  78644.1  78873.8 -39298.1  78596.1   105586 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -11.2266   0.1580   0.2543   0.4171   3.7824 
## 
## Random effects:
##  Groups    Name        Variance Std.Dev.
##  studentId (Intercept) 0.7422   0.8615  
## Number of obs: 105610, groups:  studentId, 283
## 
## Fixed effects:
##              Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  1.565915   0.060601  25.840  < 2e-16 ***
## fsfat        0.192314   0.005003  38.442  < 2e-16 ***
## hsta1       -0.952244   0.016145 -58.980  < 2e-16 ***
## nicc1        0.623305   0.135571   4.598 4.27e-06 ***
## nicc2        0.331299   0.054191   6.114 9.74e-10 ***
## nicc3       -0.247856   0.027513  -9.009  < 2e-16 ***
## nicc4       -0.014195   0.036763  -0.386 0.699402    
## nicc5       -0.183080   0.035432  -5.167 2.38e-07 ***
## nicc6       -0.256486   0.035157  -7.295 2.98e-13 ***
## gpow         0.123848   0.033556   3.691 0.000224 ***
## lectureId1  -1.018070   0.024856 -40.959  < 2e-16 ***
## lectureId2   0.017850   0.033273   0.536 0.591628    
## lectureId3   0.558622   0.044085  12.672  < 2e-16 ***
## lectureId4  -0.547061   0.026746 -20.454  < 2e-16 ***
## lectureId5  -0.170183   0.030146  -5.645 1.65e-08 ***
## lectureId6   0.138075   0.034613   3.989 6.63e-05 ***
## lectureId7   0.291268   0.037391   7.790 6.72e-15 ***
## lectureId8   0.447420   0.045693   9.792  < 2e-16 ***
## lectureId9   0.288598   0.044901   6.427 1.30e-10 ***
## lectureId10 -0.088576   0.036978  -2.395 0.016602 *  
## lectureId11  0.062259   0.039052   1.594 0.110879    
## lectureId12  0.145584   0.039316   3.703 0.000213 ***
## fsfat:hsta1  0.027901   0.004562   6.116 9.57e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{verbatim}
## 
## Correlation matrix not shown by default, as p = 23 > 12.
## Use print(x, correlation=TRUE)  or
##     vcov(x)        if you need it
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(ans42)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: correct ~ fsfat * hsta + nicc + gpow + lectureId + (1 + fsfat *  
##     hsta | studentId)
##    Data: hashTest2
## Control: glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e+05))
## 
##      AIC      BIC   logLik deviance df.resid 
##  77962.3  78278.0 -38948.2  77896.3   105577 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -13.6590   0.1379   0.2467   0.4156   3.1668 
## 
## Random effects:
##  Groups    Name        Variance Std.Dev. Corr             
##  studentId (Intercept) 0.675882 0.82212                   
##            fsfat       0.024972 0.15803   0.02            
##            hsta1       0.072061 0.26844  -0.31  0.12      
##            fsfat:hsta1 0.003271 0.05719   0.50 -0.01 -0.60
## Number of obs: 105610, groups:  studentId, 283
## 
## Fixed effects:
##              Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  1.477046   0.059899  24.659  < 2e-16 ***
## fsfat        0.259132   0.012380  20.931  < 2e-16 ***
## hsta1       -0.881182   0.025763 -34.203  < 2e-16 ***
## nicc1        0.626590   0.135552   4.623 3.79e-06 ***
## nicc2        0.340028   0.054450   6.245 4.24e-10 ***
## nicc3       -0.251857   0.027567  -9.136  < 2e-16 ***
## nicc4       -0.013454   0.036861  -0.365  0.71512    
## nicc5       -0.185017   0.035551  -5.204 1.95e-07 ***
## nicc6       -0.257133   0.035274  -7.290 3.11e-13 ***
## gpow         0.118689   0.036084   3.289  0.00100 ** 
## lectureId1  -1.027480   0.025664 -40.036  < 2e-16 ***
## lectureId2   0.016464   0.033579   0.490  0.62392    
## lectureId3   0.572888   0.044263  12.943  < 2e-16 ***
## lectureId4  -0.573858   0.027279 -21.036  < 2e-16 ***
## lectureId5  -0.166690   0.030503  -5.465 4.64e-08 ***
## lectureId6   0.140893   0.034812   4.047 5.18e-05 ***
## lectureId7   0.301169   0.037644   8.000 1.24e-15 ***
## lectureId8   0.452285   0.045846   9.865  < 2e-16 ***
## lectureId9   0.293143   0.045167   6.490 8.57e-11 ***
## lectureId10 -0.088364   0.037386  -2.364  0.01810 *  
## lectureId11  0.062045   0.039242   1.581  0.11385    
## lectureId12  0.148848   0.039586   3.760  0.00017 ***
## fsfat:hsta1  0.014892   0.007534   1.977  0.04808 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{verbatim}
## 
## Correlation matrix not shown by default, as p = 23 > 12.
## Use print(x, correlation=TRUE)  or
##     vcov(x)        if you need it
\end{verbatim}

Sést að það er einhver munur hér á milli við styrkleika breytanna. Sem passar frá muninum þeirra.

Ef við skoðum aðeins Anova hjá þeim báðum

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{Anova}\NormalTok{(ans22, }\DataTypeTok{type =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Deviance Table (Type III Wald chisquare tests)
## 
## Response: correct
##                Chisq Df Pr(>Chisq)    
## (Intercept)  667.695  1  < 2.2e-16 ***
## fsfat       1477.763  1  < 2.2e-16 ***
## hsta        3478.680  1  < 2.2e-16 ***
## nicc         172.253  6  < 2.2e-16 ***
## gpow          13.622  1  0.0002235 ***
## lectureId   2128.746 12  < 2.2e-16 ***
## fsfat:hsta    37.411  1   9.57e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{Anova}\NormalTok{(ans42, }\DataTypeTok{type =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Deviance Table (Type III Wald chisquare tests)
## 
## Response: correct
##                 Chisq Df Pr(>Chisq)    
## (Intercept)  608.0674  1  < 2.2e-16 ***
## fsfat        438.1232  1  < 2.2e-16 ***
## hsta        1169.8764  1  < 2.2e-16 ***
## nicc         177.1123  6  < 2.2e-16 ***
## gpow          10.8193  1   0.001004 ** 
## lectureId   2102.7021 12  < 2.2e-16 ***
## fsfat:hsta     3.9071  1   0.048082 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Þá lítur út fyrir að allar breyturnar eru marktækar hjá þeim.

\hypertarget{model-comparison}{%
\subsection{Model comparison}\label{model-comparison}}

Hvor er svo sterkari? Skoðum aðeins anova milli þeirra

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{anova}\NormalTok{(ans22, ans42)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Data: hashTest2
## Models:
## ans22: correct ~ fsfat * hsta + nicc + gpow + lectureId + (1 | studentId)
## ans42: correct ~ fsfat * hsta + nicc + gpow + lectureId + (1 + fsfat * 
## ans42:     hsta | studentId)
##       npar   AIC   BIC logLik deviance  Chisq Df Pr(>Chisq)    
## ans22   24 78644 78874 -39298    78596                         
## ans42   33 77962 78278 -38948    77896 699.83  9  < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Lítur út fyrir að ans42 er betra, það getur passað þar sem það er meira leift. En vandinn er að seinni modelið tekur u.þ.b. tvöfalt lengri tíma að keyra í hvert sinn, svo þá kemur spurninginn ``hve mikið betri er seinni miðað við fyrri?''

Setjum upp fall fyrir BrierScore og reiknum svo það fyrir þau bæði

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{BrierScore <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(modl, df ) \{}
\NormalTok{  predicted <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(modl, }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{  truth <-}\StringTok{ }\NormalTok{df}\OperatorTok{$}\NormalTok{correct}
  \KeywordTok{return}\NormalTok{(}\KeywordTok{mean}\NormalTok{((predicted}\OperatorTok{-}\NormalTok{truth)}\OperatorTok{^}\DecValTok{2}\NormalTok{))}
\NormalTok{\}}

\NormalTok{br22 <-}\StringTok{ }\KeywordTok{BrierScore}\NormalTok{(ans22, hashLim100)}
\NormalTok{br42 <-}\StringTok{ }\KeywordTok{BrierScore}\NormalTok{(ans42, hashLim100)}

\NormalTok{br22}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1144404
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{br42}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.11211
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{br22}\OperatorTok{-}\NormalTok{br42}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.002330465
\end{verbatim}

Nú er brierScore-ið hjá seinna minna, en bara um u.þ.b. 0.00233. Ég játa að ég veit ekki alveg enn hvað það þýðir milli styrkleikjanna þeirra, hvort það sé rosalega mikill munur eða bara smár munur.

Næst er að reikna AUC þeirra.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Auc22 <-}\StringTok{ }\KeywordTok{AUC}\NormalTok{(}\KeywordTok{predict}\NormalTok{(ans22, }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{), hashLim100}\OperatorTok{$}\NormalTok{correct)}
\NormalTok{Auc42 <-}\StringTok{ }\KeywordTok{AUC}\NormalTok{(}\KeywordTok{predict}\NormalTok{(ans42, }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{), hashLim100}\OperatorTok{$}\NormalTok{correct)}

\NormalTok{Auc22}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8205122
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Auc42}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8311404
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Auc42 }\OperatorTok{-}\StringTok{ }\NormalTok{Auc22}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01062822
\end{verbatim}

Hér sést að AUC er stærra hjá seinna modelinu en fyrra, um 0.010628. Ef ég skil Auc rétt, þá er seinni modelið með betra AUC.

En er þetta betra Brier og betra AUC nokkuð nógu mikið betra til að leifa tvöfalt lengri keyrslutíma fyrir eitthvað sem tekur svona langan tíma? Er ekki ennþá viss.

\end{document}
